### ISSUE TITLE
Failing Travis Build

### ISSUE THREAD

**Issue by dav1d-wright** [HSR-Stud/EmbHardw#1]
Irgendwas läuft beim Travis build schief.

Die Fehlermeldung tritt auf, weil die LaTeX Installation von Travis das Kommando \RedeclareSectionCommands im Header nicht kennt.

Im header2.0 habe ich vor kurzem für Koma Dokumente die Paragraph/Subparagraph headings angepasst , wofür ich dieses Kommando verwenden musste. Sind da vielleicht irgendwelche Packages nicht installiert?

**Comment by dav1d-wright** [comment]
@LukiLeu Du bist doch der Travis-Chef? Scheinbar muss für dieses Kommando Koma-Script v. 3.15 installiert sein. Ich habe beim Travis-Skript gesehen, dass TeXLive über das Debian Package installiert wird. Erfahrungsgemäss ist das nicht sehr aktuell, kann man das vielleicht untersuchen? Ich weiss auch nicht genau wie Travis aufgebaut ist, ich kenne mich eher mit Jenkins aus. Vielleicht müsste man nachschauen ob jemand anders ein aktuelleres Package zur verfügung stellt, oder das direkt von https://www.tug.org/texlive/acquire-netinstall.html herunterladen.

**Comment by LukiLeu** [comment]
Ich werde spätestens Ende nächster Woche, wenn ich dann anfange EmbHardw für die Prüfung vorzubereiten, dass ganze mal genauer noch untersuchen.

Der Build mit Travis ist ja nicht so dringend.

**Comment by LukiLeu** [comment]
@wrd90 Ich habe nun das aktuellste Texlive manuell eingebunden. Aktuell werden jedoch alle verfügbaren Pakete installiert und dann gechached. Dies kann man noch ändern, so dass nur die wirklich benötigten Pakete installiert werden.

**Comment by LMazzole** [comment]
Man könnte evt. auch ein alg. Travsirepo schreiben und als Submodul einbinden. Die Texlive installation sollte ja überall etwa die gleiche sein.  Hier wäre mein Ansatz: [Travis](https://github.com/HSR-Stud/Travis)

**Comment by dav1d-wright** [comment]
@LukiLeu super vielen Dank fürs fixen. Ich lasse das Issue noch offen für den Vorschlag von @LMazzole

**Comment by HBadertscher** [comment]
Hoi zäme

Ich finde es sehr cool dass wir jetzt mit Travis die Zusammenfassungen builden können, doch wenn eine ZF in aktiver Entwicklung ist, wie z.B. hier scheint es mir etwas unübersichtlich bei jedem Commit zu builden: hier haben wir schon 22 Releases.

Könnte man einstellen dass z.B. nur Tags ge-buildet werden? Z.B. `2018` oder `v1.0` oder so? Dann ist auch klar, welches fertige ZF's sind, und was work-in-progress ist. Was meint ihr dazu?

**Comment by dav1d-wright** [comment]
Hoi @HBadertscher ,

da stimme ich dir absolut zu.

**Comment by dav1d-wright** [comment]
@LukiLeu @HBadertscher Ich habe soeben alle alten Tags und Releases gelöscht, und ein Tag v1.0 erstellt, damit wir einen Releasestand haben für die Prüfung morgen (und als Test :)). Ich habe ebenfalls die Travis Config angepasst. Gemäss der Doku werden nur Tags deployed wenn man die option deploy.on.tags: true setzt, was ich gemacht habe. Wenn ich das richtig verfolgt habe im Travis UI, wurde der build gestartet, aber nicht deployed, was ich so richtig finde. Damit haben wir eine information welcher commit allenfalls einen fehlerhaften Build verursacht hat, auch wenn es keinen Tag hat, und trotzdem nur für Tags ein deployment.

**Comment by dav1d-wright** [comment]
Fixed by 00d407dd0143a81c3840b11fc27a1063fc11d77d
